CREATE TABLE `factor_data` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `stock_code` varchar(20) NOT NULL COMMENT '股票代码，如000001.XSHE',
  `stock_name` varchar(50) DEFAULT '' COMMENT '股票名称',
  `cube_of_size` double DEFAULT NULL COMMENT 'size的立方',
  `MFI14` double DEFAULT NULL COMMENT 'MFI指标14',
  `Skewness20` double DEFAULT NULL COMMENT '20日偏度',
  `financial_assets` double DEFAULT NULL COMMENT '金融资产',
  `bear_power` double DEFAULT NULL COMMENT '空头力量',
  `PSY` double DEFAULT NULL COMMENT '心理线',
  `Kurtosis120` double DEFAULT NULL COMMENT '120日峰度',
  `VMACD` double DEFAULT NULL COMMENT '量MACD',
  `single_day_VPT` double DEFAULT NULL COMMENT '单日VPT',
  `interest_free_current_liability` double DEFAULT NULL COMMENT '无息流动负债',
  `BIAS60` double DEFAULT NULL COMMENT '60日乖离率',
  `ATR6` double DEFAULT NULL COMMENT '6日ATR',
  `sales_to_price_ratio` double DEFAULT NULL COMMENT '市销率倒数',
  `cash_flow_to_price_ratio` double DEFAULT NULL COMMENT '现金流价格比',
  `Rank1M` double DEFAULT NULL COMMENT '1月涨幅排名',
  `Kurtosis60` double DEFAULT NULL COMMENT '60日峰度',
  `fifty_two_week_close_rank` double DEFAULT NULL COMMENT '52周收盘价排名',
  `arron_up_25` double DEFAULT NULL COMMENT 'Aroon上升指标',
  `Kurtosis20` double DEFAULT NULL COMMENT '20日峰度',
  `daily_standard_deviation` double DEFAULT NULL COMMENT '日标准差',
  `Skewness60` double DEFAULT NULL COMMENT '60日偏度',
  `single_day_VPT_12` double DEFAULT NULL COMMENT '单日VPT_12',
  `earnings_yield` double DEFAULT NULL COMMENT '盈利收益率',
  `leverage` double DEFAULT NULL COMMENT '杠杆率',
  `CR20` double DEFAULT NULL COMMENT '20日CR',
  `VOSC` double DEFAULT NULL COMMENT '量震荡指标',
  `price_no_fq` double DEFAULT NULL COMMENT '不复权价格',
  `Variance20` double DEFAULT NULL COMMENT '20日方差',
  `WVAD` double DEFAULT NULL COMMENT '威廉变异离散量',
  `ROC120` double DEFAULT NULL COMMENT '120日ROC',
  `money_flow_20` double DEFAULT NULL COMMENT '20日资金流',
  `circulating_market_cap` double DEFAULT NULL COMMENT '流通市值',
  `book_to_price_ratio` double DEFAULT NULL COMMENT '市净率倒数',
  `MAWVAD` double DEFAULT NULL COMMENT 'WVAD移动平均',
  `ATR14` double DEFAULT NULL COMMENT '14日ATR',
  `turnover_volatility` double DEFAULT NULL COMMENT '换手波动率',
  `momentum` double DEFAULT NULL COMMENT '动量',
  `MASS` double DEFAULT NULL COMMENT '梅斯线',
  `VEMA5` double DEFAULT NULL COMMENT '量EMA5',
  `DAVOL5` double DEFAULT NULL COMMENT '5日平均换手比',
  `natural_log_of_market_cap` double DEFAULT NULL COMMENT '市值对数',
  `arron_down_25` double DEFAULT NULL COMMENT 'Aroon下降指标',
  `VDIFF` double DEFAULT NULL COMMENT '量差',
  `liquidity` double DEFAULT NULL COMMENT '流动性',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_date_code` (`trade_date`,`stock_code`),
  KEY `idx_trade_date` (`trade_date`),
  KEY `idx_stock_code` (`stock_code`)
) ENGINE=InnoDB AUTO_INCREMENT=37302 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='因子数据表';